### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by alexanderwintzeus** [alexthegithubber/git-gh-crash-course#1]
I think it might look better if the main title is a darker shade of orange.

The styling rule could be changed like this:

```css
h1 {
  color: #efa82e;
}
```
